In [15]:
import pandas as pd
from sqlalchemy import create_engine

In [16]:
# PostgreSQL connection
engine = create_engine("postgresql+psycopg2://postgres:154269@localhost/bank_loan_db")
print("Connected!")

Connected!

In [17]:
query = "SELECT * FROM loan_data LIMIT 5"
df = pd.read_sql(query, engine)
df

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

In [18]:
query = "SELECT COUNT(*) FROM loan_data"
df_count = pd.read_sql(query, engine)
df_count

    count
0  150000

In [19]:
# muliple lines used triple cote """
query = """
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'loan_data'
"""
df_cols = pd.read_sql(query, engine)
df_cols

                             column_name         data_type
0                             Unnamed: 0            bigint
1                       SeriousDlqin2yrs            bigint
2   RevolvingUtilizationOfUnsecuredLines  double precision
3                                    age            bigint
4   NumberOfTime30-59DaysPastDueNotWorse            bigint
5                              DebtRatio  double precision
6                          MonthlyIncome  double precision
7        NumberOfOpenCreditLinesAndLoans            bigint
8                NumberOfTimes90DaysLate            bigint
9           NumberRealEstateLoansOrLines            bigint
10  NumberOfTime60-89DaysPastDueNotWorse            bigint
11                    NumberOfDependents  double precision

In [20]:
query = """
SELECT 
    COUNT(*) - COUNT("MonthlyIncome") as missing_income,
    COUNT(*) - COUNT("NumberOfDependents") as missing_dependents
FROM loan_data
"""
df_null = pd.read_sql(query, engine)
df_null

   missing_income  missing_dependents
0           29731                3924

In [ ]:
# group by ki query run kri jissse  ye jissem data ko alag alag category me rakh ske
query = """
SELECT "SeriousDlqin2yrs", COUNT(*) as total
FROM loan_data
GROUP BY "SeriousDlqin2yrs"
"""
group_val = pd.read_sql(query, engine)
group_val

   SeriousDlqin2yrs   total
0                 0  139974
1                 1   10026

In [25]:
# Outliers check karte hain.
query = """
SELECT
    MIN("MonthlyIncome") as min_income,
    MAX("MonthlyIncome") as max_income,
    AVG("MonthlyIncome") as avg_income
FROM loan_data
""" 
df_income = pd.read_sql(query, engine)
df_income

   min_income  max_income   avg_income
0         0.0   3008750.0  6670.221237

In [27]:
# Ab Median check karte hain
query = """
SELECT PERCENTILE_CONT(0.5)
WITHIN GROUP (ORDER BY "MonthlyIncome") as median_income
FROM loan_data
WHERE "MonthlyIncome" IS NOT NULL
"""
df_median = pd.read_sql(query, engine)
df_median

   median_income
0         5400.0