In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
# PostgreSQL connection
engine = create_engine("postgresql+psycopg2://postgres:154269@localhost/bank_loan_db")
print("Connected!")

Connected!

In [4]:
query = "SELECT * FROM loan_data LIMIT 5"
df = pd.read_sql(query, engine)
df

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

In [5]:
query = "SELECT COUNT(*) FROM loan_data"
df_count = pd.read_sql(query, engine)
df_count

    count
0  150000

In [6]:
# muliple lines used triple cote """
query = """
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'loan_data'
"""
df_cols = pd.read_sql(query, engine)
df_cols

                             column_name         data_type
0                             Unnamed: 0            bigint
1                       SeriousDlqin2yrs            bigint
2   RevolvingUtilizationOfUnsecuredLines  double precision
3                                    age            bigint
4   NumberOfTime30-59DaysPastDueNotWorse            bigint
5                              DebtRatio  double precision
6                          MonthlyIncome  double precision
7        NumberOfOpenCreditLinesAndLoans            bigint
8                NumberOfTimes90DaysLate            bigint
9           NumberRealEstateLoansOrLines            bigint
10  NumberOfTime60-89DaysPastDueNotWorse            bigint
11                    NumberOfDependents  double precision

In [7]:
query = """
SELECT 
    COUNT(*) - COUNT("MonthlyIncome") as missing_income,
    COUNT(*) - COUNT("NumberOfDependents") as missing_dependents
FROM loan_data
"""
df_null = pd.read_sql(query, engine)
df_null

   missing_income  missing_dependents
0           29731                3924

In [8]:
# group by ki query run kri jissse  ye jissem data ko alag alag category me rakh ske
query = """
SELECT "SeriousDlqin2yrs", COUNT(*) as total
FROM loan_data
GROUP BY "SeriousDlqin2yrs"
"""
group_val = pd.read_sql(query, engine)
group_val

   SeriousDlqin2yrs   total
0                 0  139974
1                 1   10026

In [9]:
# Outliers check karte hain.
query = """
SELECT
    MIN("MonthlyIncome") as min_income,
    MAX("MonthlyIncome") as max_income,
    AVG("MonthlyIncome") as avg_income
FROM loan_data
""" 
df_income = pd.read_sql(query, engine)
df_income

   min_income  max_income   avg_income
0         0.0   3008750.0  6670.221237

In [10]:
# Ab Median check karte hain monthly income ke liye
query = """
SELECT PERCENTILE_CONT(0.5)
WITHIN GROUP (ORDER BY "MonthlyIncome") as median_income
FROM loan_data
WHERE "MonthlyIncome" IS NOT NULL
"""
df_median = pd.read_sql(query, engine)
df_median

   median_income
0         5400.0

In [11]:
# Ab Median check karte hain NumberOfDependents ke liye
query = """
SELECT PERCENTILE_CONT(0.5)
WITHIN GROUP (ORDER BY "NumberOfDependents") as number_of_dependents
FROM loan_data
WHERE "NumberOfDependents" IS NOT NULL
"""
df_median = pd.read_sql(query, engine)
df_median

   number_of_dependents
0                   0.0

In [12]:
# Ab SQL se check karo — Age mein outliers hain?
query = """
SELECT
    MIN(age) as min_age,
    MAX(age) as max_age,
    AVG(age) as avg_age
FROM loan_data
"""
df_age = pd.read_sql(query, engine)
df_age

   min_age  max_age    avg_age
0        0      109  52.295207

In [13]:
query = """
SELECT COUNT(*) as outlier_age
FROM loan_data
WHERE age = 0 or age > 95
"""
df_age = pd.read_sql(query, engine)
df_age

   outlier_age
0           64

In [14]:
query = """
SELECT
    MIN("RevolvingUtilizationOfUnsecuredLines") as min_val,
    MAX("RevolvingUtilizationOfUnsecuredLines") as max_val
FROM loan_data
"""
df_revolving = pd.read_sql(query, engine)
df_revolving

   min_val  max_val
0      0.0  50708.0

In [15]:
query = """
SELECT COUNT(*) FROM loan_data where "RevolvingUtilizationOfUnsecuredLines" > 1;
"""
credit_count = pd.read_sql(query, engine)
credit_count

   count
0   3321

In [16]:
query = """
SELECT
    MIN("DebtRatio") as min_debt,
    MAX("DebtRatio") as max_debt,
    AVG("DebtRatio") as avd_debt
FROM loan_data
"""
debt_ratio = pd.read_sql(query, engine)
debt_ratio

   min_debt  max_debt    avd_debt
0       0.0  329664.0  353.005076

In [17]:
query = """
SELECT
    PERCENTILE_CONT(0.99)
    WITHIN GROUP (ORDER BY "DebtRatio") as p99_debtratio
FROM loan_data
"""
percent_cont = pd.read_sql(query, engine)
percent_cont

   p99_debtratio
0        4979.04

In [18]:
query = """
SELECT 
    PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY "DebtRatio") as p95,
    PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER BY "DebtRatio") as p90
FROM loan_data
"""
percent_95 = pd.read_sql(query, engine)
percent_95

      p95     p90
0  2449.0  1267.0

In [19]:
query = """
SELECT
    MAX("NumberOfTime30-59DaysPastDueNotWorse") as max_30_59,
    MAX("NumberOfTime60-89DaysPastDueNotWorse") as max_60_89,
    MAX("NumberOfTimes90DaysLate") as max_90
FROM loan_data
"""
df_max = pd.read_sql(query, engine)
df_max

   max_30_59  max_60_89  max_90
0         98         98      98

In [20]:
# Nayi query likhni hai — kitne rows hain jahan value = 98?
query = """
SELECT COUNT(*) FROM loan_data WHERE "NumberOfTime30-59DaysPastDueNotWorse" = 98 OR "NumberOfTime60-89DaysPastDueNotWorse" = 98 OR "NumberOfTimes90DaysLate" = 98
"""
data = pd.read_sql(query, engine)
data

   count
0    264

In [21]:
query = """
SELECT
    MIN("NumberOfOpenCreditLinesAndLoans") as min_val,
    MAX("NumberOfOpenCreditLinesAndLoans") as max_val,
    AVG("NumberOfOpenCreditLinesAndLoans") as avg_val
FROM loan_data
"""
num_credit = pd.read_sql(query, engine)
num_credit

   min_val  max_val  avg_val
0        0       58  8.45276

In [29]:
query = """
SELECT COUNT(*) FROM loan_data WHERE "NumberOfOpenCreditLinesAndLoans" > 30;
"""
max_ac = pd.read_sql(query, engine)
max_ac

   count
0    354

In [30]:
query = """
SELECT
    MIN("NumberRealEstateLoansOrLines") as min_loan,
    MAX("NumberRealEstateLoansOrLines") as max_loan,
    AVG("NumberRealEstateLoansOrLines") as avg_loan
FROM loan_data
"""
real_est_loan = pd.read_sql(query, engine)
real_est_loan

   min_loan  max_loan  avg_loan
0         0        54   1.01824

In [31]:
query = """
SELECT COUNT(*) FROM loan_data WHERE "NumberRealEstateLoansOrLines" >10;
"""
max_count_loan = pd.read_sql(query, engine)
max_count_loan

   count
0     94

# Ab Preprocessing start karte hain.